### ISSUE TITLE
Settings for Arduino RP2040 Connect

### ISSUE THREAD

**Issue by RickorDD** [sandeepmistry/pico-microphone#15]
what is the correct setting for MP34DT05 at Arduino RP2040 Connect?
Pin Data:22,Clk:23 not running.
Microphone 20000Hz? 

Thanks.

**Comment by RickorDD** [comment]
Now is Running with 
Pin Data 22
Pin Clk 23
SampleRate 16000Hz
Sample_Buffer 512

src/pdm_microphone.c
PDM_DECIMATION  128

**Comment by sandeepmistry** [comment]
Hi @RickorDD, I'm closing this as resolved.

**Comment by brian-smith-github** [comment]
Can I add that the main problem is that the code is assuming that the left/right select pin is tied low so that samples are clocked in on rising edge, however the RP2040 Connect has the select pin tied high so that samples are clocked in on falling edge. Modifying the pdm_microphone.pio file to clock in samples on falling instead of rising edge also fixes this.
